# Modified from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  run_make:
    description: Run a make command 
    parameters:
      make_cmd:
        description: Command to pass to Make
        type: string
    environment:
      MAKE_CMD: << parameters.make_cmd >>
    docker:
      - image: docker
    working_directory: ~/synbols
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add build-base freetype-dev g++ gcc gfortran git hdf5-dev icu-dev lapack-dev libffi-dev make musl-dev openblas-dev openssl-dev py3-pip py3-wheel python3-dev
            ln -s $(which python3) /usr/bin/python
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -r docker/requirements.txt
            pip install flake8 pytest
      - run:
          name: Run Make Command
          command: |
            PYTHONPATH=~/synbols
            make $MAKE_CMD
  build_docs:
    description: Build Sphinx docs
    docker:
      - image: python:3.8
    working_directory: ~/synbols/docs
    steps:
      - run:
          name: Install dependencies
          command: |
            pip install sphinx
      - checkout
      - run:
          name: Build Docs
          command: |
            cd docs
            make html
            
workflows:
  synbols:
    jobs:
      - run_make:
          name: "Run Tests"
          make_cmd: "run_tests"
      - run_make:
          name: "Run Flake8"
          make_cmd: "run_flake8"
      - build_docs
