# Modified from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  run_make:
    description: Run a make command 
    parameters:
      make_cmd:
        description: Command to pass to Make
        type: string
    environment:
      MAKE_CMD: << parameters.make_cmd >>
    docker:
      - image: docker
    working_directory: ~/synbols
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add gcc git libffi-dev make musl-dev openssl-dev py3-pip python3-dev
            ln -s $(which python3) /usr/bin/python
      - checkout
      - run:
          name: Run Make Command
          command: |
            make $MAKE_CMD
  build_docs:
    description: Build Sphinx docs
    docker:
      - image: python:3.8
    working_directory: ~/synbols/docs
    steps:
      - run:
          name: Install dependencies
          command: |
            pip install sphinx
      - checkout
      - run:
          name: Build Docs
          command: |
            cd docs
            make $MAKE_CMD
            
workflows:
  synbols:
    jobs:
      - run_make:
          make_cmd: "package"
