# Modified from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  run_make:
    description: Run a make command 
    parameters:
      make_cmd:
        description: Command to pass to Make
        type: string
    environment:
      MAKE_CMD: << parameters.make_cmd >>
    docker:
      - image: aldro61/synbols:v1.0.2
    working_directory: ~/synbols
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install flake8 pytest
      - run:
          name: Run Make Command
          command: |
            export PYTHONPATH=~/synbols
            PYTHONPATH=`pwd` make $MAKE_CMD
  build_docs:
    description: Build Sphinx docs
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r docs/requirements.txt
      - run:
          name: Build Docs
          command: |
            make build_docs            
            
workflows:
  synbols:
    jobs:
      - run_make:
          name: "Run Tests"
          make_cmd: "run_tests"
      - run_make:
          name: "Run Flake8"
          make_cmd: "run_flake8"
      - build_docs
