# Modified from https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  run_make:
    description: Run a make command 
    parameters:
      make_cmd:
        description: Command to pass to Make
        type: string
    environment:
      MAKE_CMD: << parameters.make_cmd >>
    docker:
      - image: ubuntu
    working_directory: ~/synbols
    steps:
      - run:
          name: Install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y curl fonts-cantarell fontconfig git icu-devtools ipython3 jq libcairo2-dev libhdf5-dev pkg-config python3 python3-pip ttf-ubuntu-font-family unzip wget
      - checkout
      - run:
          name: Install requirements
          command: |
            pip3 install -r docker/requirements.txt
            pip3 install flake8 pytest
      - run:
          name: Run Make Command
          command: |
            export PYTHONPATH=~/synbols
            make $MAKE_CMD
  build_docs:
    description: Build Sphinx docs
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r docs/sphinx-requirements.txt
      - run:
          name: Build Docs
          command: |
            make build_docs
  run_tests:
    description: Run unit tests
    docker:
      - image: aldro61/synbols:v0.1.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest
      - run:
          name: Build Docs
          command: |
            export PYTHONPATH=`pwd`/synbols
            make run_tests
            
workflows:
  synbols:
    jobs:
      - run_make:
          name: "Run Tests"
          make_cmd: "run_tests"
      - run_make:
          name: "Run Flake8"
          make_cmd: "run_flake8"
      - build_docs
      - run_tests
